services:
  is-it-time-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Expose web interface
    environment:
      # point agents at the MCP gateway
      - MCPGATEWAY_ENDPOINT=http://mcp-gateway:8811/sse
    depends_on:
      - mcp-gateway
    models:
      gemma3:
        endpoint_var: MODEL_RUNNER_URL
        model_var: MODEL_RUNNER_MODEL

  mcp-gateway:
    # mcp-gateway secures your MCP servers
    image: docker/mcp-gateway:latest
    use_api_socket: true
    
    command:
      - --transport=sse
      # add any MCP servers you want to use
      - --servers=time

models:
  gemma3:
    # Use a smaller model for easy testing
    model: ai/gemma3:4B-Q4_0
    context_size: 10000 # 3.5 GB VRAM